
services:
  - type: web
    name: ai-db-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: TOGETHER_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false